CREATE TABLE if not exists tb_exercise ( id bigint generated by default AS identity, name varchar(255) unique, image varchar(255), primary key (id) );

-- Idempotent seed: insert rows only if name is not present
INSERT INTO tb_exercise (name, image) VALUES
	('Flexão', 'https://i.imgur.com/zbBLV1t.png'),
	('Supino Inclinado', 'https://i.imgur.com/hLl9NKv.png'),
	('Puxada com Triângulo', 'https://i.imgur.com/HELlBze.png'),
	('Rosca Barra W', 'https://i.imgur.com/SvzC9zg.png'),
	('Tríceps Testa', 'https://i.imgur.com/5WNjy4g.png'),
	('Leg Press 45°', 'https://i.imgur.com/eJz6xv3.png'),
	('Rosca Scott', 'https://i.imgur.com/8PifBi0.png'),
	('Leg Press Horizontal', 'https://i.imgur.com/VNXi6vK.png'),
	('Agachamento Livre', 'https://i.imgur.com/uh01OOh.png'),
	('Cadeira Extensora', 'https://i.imgur.com/vtuaK5F.png'),
	('Cross Over', 'https://i.imgur.com/F092gwl.png'),
	('Remada Curvada', 'https://i.imgur.com/usRrRIb.png'),
	('Puxada', 'https://i.imgur.com/AOvz0PY.png'),
	('Tríceps Polia', 'https://i.imgur.com/9nhspju.png'),
	('Desenvolvimento', 'https://i.imgur.com/nfrS3jS.png')
ON CONFLICT (name) DO NOTHING;

-- Ensure identity sequence advances beyond current max id
SELECT setval(pg_get_serial_sequence('tb_exercise','id'), (SELECT COALESCE(MAX(id),1) FROM tb_exercise));