CREATE TABLE if not exists tb_role (id bigint generated by default AS identity, authority varchar(255), primary key (id));

CREATE TABLE if not exists tb_user (id bigint generated by default AS identity, email varchar(255) unique, name varchar(255), password varchar(255), primary key (id));

CREATE TABLE if not exists tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));

INSERT INTO tb_role (id, authority)
SELECT 1, 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM tb_role WHERE id = 1 OR authority = 'ROLE_ADMIN');

INSERT INTO tb_role (id, authority)
SELECT 2, 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM tb_role WHERE id = 2 OR authority = 'ROLE_USER');