create table if not exists tb_workout (date TIMESTAMP WITHOUT TIME ZONE, id bigint generated by default as identity, user_id bigint, name varchar(255), primary key (id));
create table if not exists tb_workout_item (rest integer, set_number integer, weight integer, exercise_id bigint, id bigint generated by default as identity, workout_id bigint, reps varchar(255), primary key (id));
