services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - netApp
  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - netApp
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - user-db
    networks:
      - netApp
networks:
  netApp:
    driver: bridge