INSERT INTO tb_exercise (name, image) VALUES ('Flexão', 'https://i.imgur.com/zbBLV1t.png');
INSERT INTO tb_exercise (name, image) VALUES ('Supino Inclinado', 'https://i.imgur.com/hLl9NKv.png');
INSERT INTO tb_exercise (name, image) VALUES ('Puxada com Triângulo', 'https://i.imgur.com/HELlBze.png');
INSERT INTO tb_exercise (name, image) VALUES ('Rosca Barra W', 'https://i.imgur.com/SvzC9zg.png');
INSERT INTO tb_exercise (name, image) VALUES ('Tríceps Testa', 'https://i.imgur.com/5WNjy4g.png');
INSERT INTO tb_exercise (name, image) VALUES ('Leg Press 45°', 'https://i.imgur.com/eJz6xv3.png');
INSERT INTO tb_exercise (name, image) VALUES ('Rosca Scott', 'https://i.imgur.com/8PifBi0.png');
INSERT INTO tb_exercise (name, image) VALUES ('Leg Press Horizontal', 'https://i.imgur.com/VNXi6vK.png');
INSERT INTO tb_exercise (name, image) VALUES ('Agachamento Livre', 'https://i.imgur.com/uh01OOh.png');
INSERT INTO tb_exercise (name, image) VALUES ('Cadeira Extensora', 'https://i.imgur.com/vtuaK5F.png');
INSERT INTO tb_exercise (name, image) VALUES ('Cross Over', 'https://i.imgur.com/F092gwl.png');
INSERT INTO tb_exercise (name, image) VALUES ('Remada Curvada', 'https://i.imgur.com/usRrRIb.png');
INSERT INTO tb_exercise (name, image) VALUES ('Puxada', 'https://i.imgur.com/AOvz0PY.png');
INSERT INTO tb_exercise (name, image) VALUES ('Tríceps Polia', 'https://i.imgur.com/9nhspju.png');
INSERT INTO tb_exercise (name, image) VALUES ('Desenvolvimento', 'https://i.imgur.com/nfrS3jS.png');